/** Données démo — promoteur multi-écoles (jeu de données isolé par établissement). */
window.PWE_MOCK = {
  schools: [
    {
      id: 'sch-faso-kanu',
      code: 'ECO-00291',
      name: 'École Faso Kanu',
      city: 'Bamako',
      commune: 'Hippodrome',
      address: 'Rue 420, Porte 12',
      phone: '+223 76 00 00 91',
      email: 'contact@fasokanu.ml',
      director: 'Mamadou Diarra',
      promoter: 'Aminata Keïta',
      academicYear: '2025-2026',
      status: 'active',
      portalStatus: 'active',
      role: 'school_owner',
      logoUrl: null,
      description:
        'École primaire et secondaire — engagement diaspora et familles de Bamako.',
      studentsCount: 620,
      classesCount: 18,
      teachersCount: 32,
      parentsLinked: 410,
    },
    {
      id: 'sch-etoiles',
      code: 'ECO-00312',
      name: 'École Les Étoiles',
      city: 'Ségou',
      commune: 'Centre',
      address: 'Avenue du Marché',
      phone: '+223 76 11 22 33',
      email: 'contact@etoiles.ml',
      director: 'Fatoumata Sissoko',
      promoter: 'Aminata Keïta',
      academicYear: '2025-2026',
      status: 'active',
      portalStatus: 'active',
      role: 'school_owner',
      logoUrl: null,
      description: 'École fondamentale — excellence et suivi des familles.',
      studentsCount: 280,
      classesCount: 10,
      teachersCount: 18,
      parentsLinked: 195,
    },
  ],

  /** @deprecated compat — utilisez schoolData */
  school: {
    id: 'sch-faso-kanu',
    code: 'ECO-00291',
    name: 'École Faso Kanu',
    city: 'Bamako',
  },

  staffSession: {
    email: 'directeur@fasokanu.ml',
    password: 'walaha-demo',
    role: 'school_director',
    name: 'Mamadou Diarra',
  },

  parentDirectory: [
    { id: 'par-1', code: 'PAR-TRAORE-A-12001', name: 'Aminata Traoré (mère)' },
    { id: 'par-2', code: 'PAR-TRAORE-I-12002', name: 'Ibrahim Traoré (père)' },
    { id: 'par-3', code: 'PAR-DIALLO-F-12003', name: 'Fatoumata Diallo' },
    { id: 'par-4', code: 'PAR-DOUMBIA-M-12001', name: 'Mariam Doumbia' },
    { id: 'par-5', code: 'PAR-SANGARE-M-12004', name: 'Mamadou Sangaré' },
    { id: 'par-6', code: 'PAR-SANGARE-A-12005', name: 'Awa Sangaré' },
  ],

  schoolData: {
    'sch-faso-kanu': {
      dashboard: {
        reportsPublished: 560,
        reportsPending: 42,
        feesPaid: 548,
        feesUnpaid: 72,
        recentMessages: 24,
        needsOpen: 8,
      },
      classes: [
        { id: 'cls-1', name: '1ère Année A', level: '1ère', year: '2025-2026', master: 'Fatoumata S.', students: 38, status: 'active' },
        { id: 'cls-2', name: '2ème Année B', level: '2ème', year: '2025-2026', master: 'Ibrahim T.', students: 35, status: 'active' },
        { id: 'cls-3', name: '6ème Année', level: '6ème', year: '2025-2026', master: 'Aïcha M.', students: 42, status: 'active' },
        { id: 'cls-4', name: '9ème Année', level: '9ème', year: '2025-2026', master: 'Oumar B.', students: 40, status: 'active' },
        { id: 'cls-5', name: 'Terminale S', level: 'Terminale', year: '2025-2026', master: 'Drissa K.', students: 28, status: 'active' },
        { id: 'cls-6', name: '7ème Année (archivée)', level: '7ème', year: '2024-2025', master: '—', students: 0, status: 'archived' },
      ],
      students: [
        { id: 'stu-1', firstName: 'Aminata', lastName: 'Traoré', classId: 'cls-3', name: 'Aminata Traoré', class: '6ème Année', code: 'ELV-10482', gender: 'F', status: 'active', parents: 2 },
        { id: 'stu-2', firstName: 'Moussa', lastName: 'Diallo', classId: 'cls-4', name: 'Moussa Diallo', class: '9ème Année', code: 'ELV-10491', gender: 'M', status: 'active', parents: 1 },
        { id: 'stu-3', firstName: 'Kadiatou', lastName: 'Sangaré', classId: 'cls-1', name: 'Kadiatou Sangaré', class: '1ère Année A', code: 'ELV-10502', gender: 'F', status: 'active', parents: 2 },
        { id: 'stu-4', firstName: 'Sekou', lastName: 'Camara', classId: 'cls-5', name: 'Sekou Camara', class: 'Terminale S', code: 'ELV-10518', gender: 'M', status: 'active', parents: 1 },
        { id: 'stu-5', firstName: 'Hawa', lastName: 'Coulibaly', classId: 'cls-2', name: 'Hawa Coulibaly', class: '2ème Année B', code: 'ELV-10533', gender: 'F', status: 'suspended', parents: 2 },
      ],
      studentParentLinks: [
        { id: 'spl-1', studentId: 'stu-1', parentCode: 'PAR-TRAORE-A-12001', parentName: 'Aminata Traoré (mère)', relationship: 'mother' },
        { id: 'spl-2', studentId: 'stu-1', parentCode: 'PAR-TRAORE-I-12002', parentName: 'Ibrahim Traoré (père)', relationship: 'father' },
        { id: 'spl-3', studentId: 'stu-2', parentCode: 'PAR-DIALLO-F-12003', parentName: 'Fatoumata Diallo', relationship: 'mother' },
        { id: 'spl-4', studentId: 'stu-3', parentCode: 'PAR-SANGARE-M-12004', parentName: 'Mamadou Sangaré', relationship: 'father' },
        { id: 'spl-5', studentId: 'stu-3', parentCode: 'PAR-SANGARE-A-12005', parentName: 'Awa Sangaré', relationship: 'mother' },
        { id: 'spl-6', studentId: 'stu-4', parentCode: 'PAR-DIALLO-F-12003', parentName: 'Fatoumata Diallo', relationship: 'guardian' },
        { id: 'spl-7', studentId: 'stu-5', parentCode: 'PAR-TRAORE-A-12001', parentName: 'Aminata Traoré (mère)', relationship: 'guardian' },
        { id: 'spl-8', studentId: 'stu-5', parentCode: 'PAR-TRAORE-I-12002', parentName: 'Ibrahim Traoré (père)', relationship: 'guardian' },
      ],
      teachers: [
        { name: 'Fatoumata Sidibé', code: 'ENS-SIDIBE-F-38401', subject: 'ENS-SIDIBE-F-38401', role: 'class_master', classes: '1ère A', status: 'active' },
        { name: 'Ibrahim Touré', code: 'ENS-TOURE-I-38412', subject: 'ENS-TOURE-I-38412', role: 'teacher', classes: '2ème B, 6ème', status: 'active' },
        { name: 'Aïcha Maïga', code: 'ENS-MAIGA-A-38425', subject: 'ENS-MAIGA-A-38425', role: 'class_master', classes: '6ème', status: 'active' },
        { name: 'Oumar Barry', code: 'ENS-BARRY-O-38433', subject: 'ENS-BARRY-O-38433', role: 'teacher', classes: '9ème', status: 'active' },
        { name: 'Mariam Doumbia', code: 'PAR-DOUMBIA-M-12001', subject: 'PAR-DOUMBIA-M-12001', role: 'school_accountant', classes: '—', status: 'active' },
      ],
      reports: [
        { student: 'Aminata Traoré', class: '6ème', term: 'T2 2025-2026', average: '14,2', status: 'published' },
        { student: 'Moussa Diallo', class: '9ème', term: 'T2 2025-2026', average: '11,8', status: 'pending' },
        { student: 'Kadiatou Sangaré', class: '1ère A', term: 'T2 2025-2026', average: '16,0', status: 'published' },
        { student: 'Sekou Camara', class: 'Terminale S', term: 'T2 2025-2026', average: '13,5', status: 'draft' },
      ],
      fees: [
        { student: 'Aminata Traoré', class: '6ème', amount: '45 000', due: '15/10/2025', status: 'paid' },
        { student: 'Moussa Diallo', class: '9ème', amount: '45 000', due: '15/10/2025', status: 'unpaid' },
        { student: 'Kadiatou Sangaré', class: '1ère A', amount: '40 000', due: '15/10/2025', status: 'paid' },
        { student: 'Hawa Coulibaly', class: '2ème B', amount: '40 000', due: '15/10/2025', status: 'partial' },
      ],
      messages: [
        { id: 'msg-fk-1', from: 'Parent — Traoré', subject: 'Réunion parents 6ème', date: '22/06/2026', unread: true, audience: 'Classe 6ème', body: 'Bonjour, pourriez-vous confirmer la date de la réunion parents de la 6ème ? Merci.' },
        { id: 'msg-fk-2', from: 'Parent — Diallo', subject: 'Justificatif absence', date: '21/06/2026', unread: false, audience: 'Élève Moussa Diallo', body: 'Voici le justificatif pour l’absence de mon fils du 19 juin. Cordialement.' },
        { id: 'msg-fk-3', from: 'Walaha — Système', subject: 'Bulletin T2 publié', date: '20/06/2026', unread: false, audience: 'Tous les parents', body: 'Les bulletins du 2e trimestre ont été publiés. Les parents peuvent les consulter dans l’application WalahaTracker.' },
      ],
      statistics: {
        students_active: 620,
        classes_active: 18,
        staff_active: 32,
        students_by_class: [
          { class_name: '1ère Année A', level: '1ère', student_count: 38 },
          { class_name: '6ème Année', level: '6ème', student_count: 42 },
          { class_name: '9ème Année', level: '9ème', student_count: 40 },
          { class_name: 'Terminale S', level: 'Terminale', student_count: 28 },
        ],
        reports_total: 602,
        reports_published: 560,
        reports_pending: 42,
        report_publish_rate: 0.93,
        fees_total: 620,
        fees_paid: 548,
        fees_unpaid: 72,
        fees_paid_amount: 24660000,
        fees_unpaid_amount: 3240000,
        announcements_count: 24,
        class_averages: [
          { class_name: '6ème Année', avg_average: 13.8, report_count: 42 },
          { class_name: '9ème Année', avg_average: 12.4, report_count: 40 },
          { class_name: 'Terminale S', avg_average: 14.1, report_count: 28 },
        ],
        students_archived: 15,
        classes_archived: 1,
      },
      activity: [
        { text: 'Bulletin T2 publié — 6ème Année', time: 'Il y a 2 h' },
        { text: 'Nouveau parent lié — ELV-10502', time: 'Il y a 5 h' },
        { text: 'Frais enregistré — Traoré Aminata', time: 'Hier' },
        { text: 'Classe Terminale S mise à jour', time: 'Hier' },
      ],
    },

    'sch-etoiles': {
      dashboard: {
        reportsPublished: 248,
        reportsPending: 18,
        feesPaid: 255,
        feesUnpaid: 25,
        recentMessages: 11,
        needsOpen: 3,
      },
      classes: [
        { id: 'cls-e1', name: 'CP1 Les Étoiles', level: 'CP', year: '2025-2026', master: 'Rokia K.', students: 32, status: 'active' },
        { id: 'cls-e2', name: 'CE2 Les Étoiles', level: 'CE2', year: '2025-2026', master: 'Seydou C.', students: 28, status: 'active' },
        { id: 'cls-e3', name: 'CM2 Les Étoiles', level: 'CM2', year: '2025-2026', master: 'Aminata D.', students: 30, status: 'active' },
      ],
      students: [
        { id: 'stu-e1', firstName: 'Binta', lastName: 'Koné', classId: 'cls-e1', name: 'Binta Koné', class: 'CP1 Les Étoiles', code: 'ELV-20101', gender: 'F', status: 'active', parents: 2 },
        { id: 'stu-e2', firstName: 'Modibo', lastName: 'Keita', classId: 'cls-e2', name: 'Modibo Keita', class: 'CE2 Les Étoiles', code: 'ELV-20112', gender: 'M', status: 'active', parents: 1 },
        { id: 'stu-e3', firstName: 'Salimata', lastName: 'Coulibaly', classId: 'cls-e3', name: 'Salimata Coulibaly', class: 'CM2 Les Étoiles', code: 'ELV-20125', gender: 'F', status: 'active', parents: 2 },
      ],
      studentParentLinks: [
        { id: 'spl-e1', studentId: 'stu-e1', parentCode: 'PAR-DIALLO-F-12003', parentName: 'Fatoumata Diallo', relationship: 'mother' },
        { id: 'spl-e2', studentId: 'stu-e1', parentCode: 'PAR-DOUMBIA-M-12001', parentName: 'Mariam Doumbia', relationship: 'guardian' },
        { id: 'spl-e3', studentId: 'stu-e2', parentCode: 'PAR-SANGARE-M-12004', parentName: 'Mamadou Sangaré', relationship: 'father' },
        { id: 'spl-e4', studentId: 'stu-e3', parentCode: 'PAR-TRAORE-A-12001', parentName: 'Aminata Traoré (mère)', relationship: 'mother' },
        { id: 'spl-e5', studentId: 'stu-e3', parentCode: 'PAR-TRAORE-I-12002', parentName: 'Ibrahim Traoré (père)', relationship: 'father' },
      ],
      teachers: [
        { name: 'Rokia Konaté', code: 'ENS-KONATE-R-40101', subject: 'ENS-KONATE-R-40101', role: 'class_master', classes: 'CP1', status: 'active' },
        { name: 'Seydou Coulibaly', code: 'ENS-COULIBALY-S-40112', subject: 'ENS-COULIBALY-S-40112', role: 'teacher', classes: 'CE2', status: 'active' },
        { name: 'Aminata Diarra', code: 'ENS-DIARRA-A-40125', subject: 'ENS-DIARRA-A-40125', role: 'class_master', classes: 'CM2', status: 'active' },
      ],
      reports: [
        { student: 'Binta Koné', class: 'CP1', term: 'T2 2025-2026', average: '15,1', status: 'published' },
        { student: 'Modibo Keita', class: 'CE2', term: 'T2 2025-2026', average: '12,9', status: 'pending' },
        { student: 'Salimata Coulibaly', class: 'CM2', term: 'T2 2025-2026', average: '14,7', status: 'published' },
      ],
      fees: [
        { student: 'Binta Koné', class: 'CP1', amount: '35 000', due: '20/10/2025', status: 'paid' },
        { student: 'Modibo Keita', class: 'CE2', amount: '35 000', due: '20/10/2025', status: 'unpaid' },
        { student: 'Salimata Coulibaly', class: 'CM2', amount: '35 000', due: '20/10/2025', status: 'paid' },
      ],
      messages: [
        { id: 'msg-et-1', from: 'Parent — Koné', subject: 'Fournitures scolaires', date: '23/06/2026', unread: true, audience: 'Classe CP1', body: 'Bonjour, la liste des fournitures pour le CP1 est-elle disponible ? Merci.' },
        { id: 'msg-et-2', from: 'École Les Étoiles', subject: 'Sortie pédagogique CM2', date: '19/06/2026', unread: false, audience: 'Classe CM2', body: 'La sortie pédagogique du CM2 est prévue le 5 juillet. Merci de confirmer la participation.' },
      ],
      statistics: {
        students_active: 280,
        classes_active: 10,
        staff_active: 18,
        students_by_class: [
          { class_name: 'CP1 Les Étoiles', level: 'CP', student_count: 32 },
          { class_name: 'CE2 Les Étoiles', level: 'CE2', student_count: 28 },
          { class_name: 'CM2 Les Étoiles', level: 'CM2', student_count: 30 },
        ],
        reports_total: 266,
        reports_published: 248,
        reports_pending: 18,
        report_publish_rate: 0.93,
        fees_total: 280,
        fees_paid: 255,
        fees_unpaid: 25,
        fees_paid_amount: 8925000,
        fees_unpaid_amount: 875000,
        announcements_count: 11,
        class_averages: [
          { class_name: 'CP1 Les Étoiles', avg_average: 14.2, report_count: 32 },
          { class_name: 'CE2 Les Étoiles', avg_average: 13.1, report_count: 28 },
          { class_name: 'CM2 Les Étoiles', avg_average: 14.5, report_count: 30 },
        ],
        students_archived: 4,
        classes_archived: 0,
      },
      activity: [
        { text: 'Inscription validée — Binta Koné', time: 'Il y a 3 h' },
        { text: 'Message envoyé — parents CP1', time: 'Hier' },
        { text: 'Frais partiel — Modibo Keita', time: 'Hier' },
      ],
    },
  },
};
